services:
  frontend:
    build:
      context: ./my-react-app
    ports:
      - "5173:5173"
    volumes:
      - ./my-react-app:/app
    depends_on:
      - backend

  backend:
    build:
      context: ./BE
    ports:
      - "5001:5001"
    volumes:
      - ./BE:/app
